apiVersion: v1
kind: Namespace
metadata:
  name:  nginx

kubectl apply -f namespace.yaml 
or 
kubectl create namespace <name>
kubectl delete ns <name>                ------------ deletes all resources in that namespace

kubectl get all -n nginx
